import React from "react";
import styles from "../styles/About.module.scss";
import { dataList } from "../dataSource/data.js";
import Head from "next/head";

function About() {
  console.log(dataList[0].name);
  return (
    <>
      <div className={styles.div}>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/images/fav/favicon.ico" />
          <title>Bacho - about</title>
        </Head>
        <p>
          Hi, Im Bacho, a beginner frontend developer. I was fascinated by
          technology since childhood and I thought that I was better at working
          with them than my relatives or friends. Unfortunately, I did not
          continue my studies in the direction of technology, and I believe that
          this was my most wrong step in my life. It is true that what a person
          loves, he will inevitably fight for it and achieve it. This happened
          in my life too. I started studying business management, but I could
          not finish it. After the end of the third year, I quit because I was
          not interested, it was not my field. The only thing I realized during
          these three years is that a person does not need to learn management
          because he cannot become a manager if he is not a manager by birth.
          lets stop talking about my past because the present and the future are
          more interesting. After all this, I started to learn programming on my
          own, and on this difficult path, I chose frontend because I like to
          see the results during work, which keeps me motivated. I believe that
          I am ready to take responsibility and immerse myself in the work flow
          so that after so much work I want to become a professional and deepen
          my knowledge. I will also say here that I plan to become a fullstuck
          developer and I will definitely do it. Thank you for your attentions.
        </p>
        <hr />
        <div className={styles.skills}>
          <p>Check my arsenal</p>
          <div className={styles.skillCont}>
            {dataList.map((item) => (
              <div key={item.name} className={styles.skillCard}>
                <div>
                  <img src={item.image} alt={item.alt} />
                </div>
                <p>{item.name}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </>
  );
}

export default About;
