import React from "react";
import styles from "../styles/Contact.module.scss";
import LocalPhoneIcon from "@mui/icons-material/LocalPhone";
import EmailIcon from "@mui/icons-material/Email";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import Head from "next/head";

function contact() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/fav/favicon.ico" />
        <title>Bacho - Contact</title>
      </Head>
      <div className={styles.main}>
        <div className={styles.contentCont}>
          <div>
            <LocalPhoneIcon className={styles.contactIcon} />
            <p>+995 591 41 90 90</p>
          </div>
          <div>
            <EmailIcon className={styles.contactIcon} />
            <p>Bacholashkhia13@gmail.com</p>
          </div>
          <div>
            <LinkedInIcon className={styles.contactIcon} />
            <p>Bacho Lashkhia</p>
          </div>
        </div>
      </div>
    </>
  );
}

export default contact;
