import Head from "next/head";
import styles from "../styles/Index.module.scss";

export default function Home() {
  return (
    <div className="globalBG">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/fav/favicon.ico" />
        <title>Bacho - Portfolio</title>
      </Head>
      <div className={styles.main}>
        <div className={styles.content}>
          <h1>I&apos;m Bacho Lashkhia.</h1>
          <h2>Junior Front-end Developer</h2>
        </div>
        <div>
          <img src="/images/profile.png" alt="" />
        </div>
      </div>
    </div>
  );
}
